// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.suns.nano;

@SuppressWarnings("hiding")
public interface SubscribeReqModel {

  public static final class SubscribeReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile SubscribeReq[] _emptyArray;
    public static SubscribeReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SubscribeReq[0];
          }
        }
      }
      return _emptyArray;
    }

    // required int32 subReqID = 1;
    public int subReqID;

    // required string userName = 2;
    public String userName;

    // required string productName = 3;
    public String productName;

    // optional string phoneNumber = 4;
    public String phoneNumber;

    public SubscribeReq() {
      clear();
    }

    public SubscribeReq clear() {
      subReqID = 0;
      userName = "";
      productName = "";
      phoneNumber = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeInt32(1, this.subReqID);
      output.writeString(2, this.userName);
      output.writeString(3, this.productName);
      if (!this.phoneNumber.equals("")) {
        output.writeString(4, this.phoneNumber);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.subReqID);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.userName);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(3, this.productName);
      if (!this.phoneNumber.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.phoneNumber);
      }
      return size;
    }

    @Override
    public SubscribeReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.subReqID = input.readInt32();
            break;
          }
          case 18: {
            this.userName = input.readString();
            break;
          }
          case 26: {
            this.productName = input.readString();
            break;
          }
          case 34: {
            this.phoneNumber = input.readString();
            break;
          }
        }
      }
    }

    public static SubscribeReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new SubscribeReq(), data);
    }

    public static SubscribeReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SubscribeReq().mergeFrom(input);
    }
  }
}
